version: "3.8"

services:
  backend:
    container_name: backend_container
    build:
      context: ./src/Backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on: 
      - mongo
      - mosquitto

  mongo:
    image: mongo:4.2
    container_name: mongo_container
    ports:
      - 27018:27017

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_container
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto.conf

  frontend:
      container_name: frontend_container
      build:
        context: ./src/Frontend
        dockerfile: Dockerfile
      ports:
        - 5173:5173
      depends_on: 
        - mongo
        - mosquitto
        - backend